import type { Tournament } from './types'

export const mockTournaments: Tournament[] = [
  {
    id: 1,
    title: 'INITIATION',
    game: 'VALORANT',
    region: 'EU',
    gameMode: '5v5',
    format: 'TEAM',
    status: 'live',
    date: 'TODAY',
    startsIn: '14H',
    teams: 64,
    entryFee: '500CR',
    prizePool: '10,000CR',
    prizeAmount: 10000,
    prizeTier: '5K+ CR',
    rank: 'GOLD+',
    artwork: 'initiation',
  },
  {
    id: 2,
    title: 'PHANTOM STRIKE',
    game: 'VALORANT',
    region: 'NA',
    gameMode: 'DEATHMATCH',
    format: 'DUO',
    status: 'live',
    date: 'TODAY',
    startsIn: '8H',
    teams: 48,
    entryFee: '400CR',
    prizePool: '8,000CR',
    prizeAmount: 8000,
    prizeTier: '5K+ CR',
    rank: 'PLATINUM+',
    artwork: 'phantom',
  },
  {
    id: 3,
    title: 'SHADOW RUSH',
    game: 'VALORANT',
    region: 'EU',
    gameMode: '5v5',
    format: 'TEAM',
    status: 'live',
    date: 'THIS WEEK',
    startsIn: '6H',
    teams: 64,
    entryFee: '300CR',
    prizePool: '6,500CR',
    prizeAmount: 6500,
    prizeTier: '5K+ CR',
    rank: 'GOLD+',
    artwork: 'shadow',
  },
  {
    id: 4,
    title: 'VANGUARD OPEN',
    game: 'VALORANT',
    region: 'EU',
    gameMode: '5v5',
    format: 'TEAM',
    status: 'live',
    date: 'THIS WEEK',
    startsIn: '24H',
    teams: 32,
    entryFee: '750CR',
    prizePool: '18,000CR',
    prizeAmount: 18000,
    prizeTier: '5K+ CR',
    rank: 'DIAMOND+',
    artwork: 'vanguard',
  },
  {
    id: 5,
    title: 'NEON CLASH',
    game: 'VALORANT',
    region: 'APAC',
    gameMode: 'DEATHMATCH',
    format: 'SOLO',
    status: 'live',
    date: 'TODAY',
    startsIn: '4H',
    teams: 256,
    entryFee: '150CR',
    prizePool: '3,500CR',
    prizeAmount: 3500,
    prizeTier: '1K-5K CR',
    rank: 'ANY',
    artwork: 'neon',
  },
  {
    id: 6,
    title: 'RADIANT TRIALS',
    game: 'VALORANT',
    region: 'EU',
    gameMode: 'PREMIER',
    format: 'TEAM',
    status: 'live',
    date: 'THIS MONTH',
    startsIn: '36H',
    teams: 64,
    entryFee: '1000CR',
    prizePool: '25,000CR',
    prizeAmount: 25000,
    prizeTier: '5K+ CR',
    rank: 'DIAMOND+',
    artwork: 'radiant',
  },
  {
    id: 7,
    title: 'CRIMSON CROWN',
    game: 'VALORANT',
    region: 'NA',
    gameMode: '5v5',
    format: 'TEAM',
    status: 'live',
    date: 'THIS WEEK',
    startsIn: '42H',
    teams: 32,
    entryFee: '500CR',
    prizePool: '14,000CR',
    prizeAmount: 14000,
    prizeTier: '5K+ CR',
    rank: 'GOLD+',
    artwork: 'crown',
  },
  {
    id: 8,
    title: 'OBSIDIAN CUP',
    game: 'VALORANT',
    region: 'EU',
    gameMode: '5v5',
    format: 'TEAM',
    status: 'upcoming',
    date: 'THIS WEEK',
    startsIn: '3D',
    teams: 64,
    entryFee: '400CR',
    prizePool: '9,000CR',
    prizeAmount: 9000,
    prizeTier: '5K+ CR',
    rank: 'GOLD+',
    artwork: 'shadow',
  },
  {
    id: 9,
    title: 'FALLEN LEGENDS',
    game: 'VALORANT',
    region: 'NA',
    gameMode: 'DEATHMATCH',
    format: 'DUO',
    status: 'ended',
    date: 'THIS MONTH',
    startsIn: '-',
    teams: 48,
    entryFee: '300CR',
    prizePool: '7,500CR',
    prizeAmount: 7500,
    prizeTier: '5K+ CR',
    rank: 'PLATINUM+',
    artwork: 'legends',
  },
  {
    id: 10,
    title: 'IRON ECLIPSE',
    game: 'VALORANT',
    region: 'CIS',
    gameMode: 'PREMIER',
    format: 'TEAM',
    status: 'upcoming',
    date: 'THIS WEEK',
    startsIn: '4D',
    teams: 32,
    entryFee: '900CR',
    prizePool: '22,000CR',
    prizeAmount: 22000,
    prizeTier: '5K+ CR',
    rank: 'DIAMOND+',
    artwork: 'crown',
  },
  {
    id: 11,
    title: 'ASHEN DUEL',
    game: 'VALORANT',
    region: 'EU',
    gameMode: 'DEATHMATCH',
    format: 'SOLO',
    status: 'upcoming',
    date: 'TODAY',
    startsIn: '18H',
    teams: 128,
    entryFee: 'FREE',
    prizePool: 'FREE',
    prizeAmount: 0,
    prizeTier: 'FREE',
    rank: 'ANY',
    artwork: 'phantom',
  },
  {
    id: 12,
    title: 'NIGHTFALL SERIES',
    game: 'VALORANT',
    region: 'APAC',
    gameMode: '5v5',
    format: 'TEAM',
    status: 'upcoming',
    date: 'THIS MONTH',
    startsIn: '12D',
    teams: 64,
    entryFee: '600CR',
    prizePool: '12,000CR',
    prizeAmount: 12000,
    prizeTier: '5K+ CR',
    rank: 'PLATINUM+',
    artwork: 'vanguard',
  },
  {
    id: 13,
    title: 'SCARLET PAIR',
    game: 'VALORANT',
    region: 'NA',
    gameMode: 'PREMIER',
    format: 'DUO',
    status: 'upcoming',
    date: 'THIS WEEK',
    startsIn: '5D',
    teams: 40,
    entryFee: '200CR',
    prizePool: '4,000CR',
    prizeAmount: 4000,
    prizeTier: '1K-5K CR',
    rank: 'GOLD+',
    artwork: 'neon',
  },
  {
    id: 14,
    title: 'FROSTBITE ARENA',
    game: 'VALORANT',
    region: 'CIS',
    gameMode: '5v5',
    format: 'TEAM',
    status: 'upcoming',
    date: 'THIS MONTH',
    startsIn: '20D',
    teams: 96,
    entryFee: '350CR',
    prizePool: '5,000CR',
    prizeAmount: 5000,
    prizeTier: '1K-5K CR',
    rank: 'ANY',
    artwork: 'radiant',
  },
  {
    id: 15,
    title: 'VOID RUNNERS',
    game: 'VALORANT',
    region: 'EU',
    gameMode: 'DEATHMATCH',
    format: 'SOLO',
    status: 'ended',
    date: 'THIS WEEK',
    startsIn: '-',
    teams: 128,
    entryFee: 'FREE',
    prizePool: '2,500CR',
    prizeAmount: 2500,
    prizeTier: '1K-5K CR',
    rank: 'ANY',
    artwork: 'legends',
  },
  {
    id: 16,
    title: 'LEGION ASCENT',
    game: 'VALORANT',
    region: 'APAC',
    gameMode: 'PREMIER',
    format: 'TEAM',
    status: 'ended',
    date: 'THIS MONTH',
    startsIn: '-',
    teams: 32,
    entryFee: '850CR',
    prizePool: '16,000CR',
    prizeAmount: 16000,
    prizeTier: '5K+ CR',
    rank: 'DIAMOND+',
    artwork: 'initiation',
  },
  {
    id: 17,
    title: 'EMBER DUO',
    game: 'VALORANT',
    region: 'CIS',
    gameMode: 'DEATHMATCH',
    format: 'DUO',
    status: 'live',
    date: 'TODAY',
    startsIn: '2H',
    teams: 24,
    entryFee: '100CR',
    prizePool: '1,500CR',
    prizeAmount: 1500,
    prizeTier: '1K-5K CR',
    rank: 'ANY',
    artwork: 'shadow',
  },
  {
    id: 18,
    title: 'SOVEREIGN FIVE',
    game: 'VALORANT',
    region: 'EU',
    gameMode: '5v5',
    format: 'TEAM',
    status: 'upcoming',
    date: 'THIS WEEK',
    startsIn: '6D',
    teams: 64,
    entryFee: '1200CR',
    prizePool: '30,000CR',
    prizeAmount: 30000,
    prizeTier: '5K+ CR',
    rank: 'DIAMOND+',
    artwork: 'radiant',
  },
]

const currencyFormat = new Intl.NumberFormat('en-US')
const prizeTotal = mockTournaments.reduce(
  (total, tournament) => total + tournament.prizeAmount,
  0,
)

export const tournamentOverview = [
  {
    label: 'LIVE NOW',
    value: String(
      mockTournaments.filter((tournament) => tournament.status === 'live').length,
    ),
    icon: 'pulse',
  },
  {
    label: 'UPCOMING',
    value: String(
      mockTournaments.filter((tournament) => tournament.status === 'upcoming')
        .length,
    ),
    icon: 'calendar',
  },
  {
    label: 'TOTAL PRIZE POOL',
    value: `${currencyFormat.format(prizeTotal)} CR`,
    icon: 'coin',
  },
  {
    label: 'REGIONS',
    value: String(
      new Set(mockTournaments.map((tournament) => tournament.region)).size,
    ),
    icon: 'globe',
  },
] as const
